### ISSUE TITLE
Compile Design Inspirations

### ISSUE THREAD

**Issue by ericahagle** [ericahagle/fitlit#4]
3 design inspirations 
- include links and details on what you’re trying to re-create

**Comment by tenthwalker** [comment]
![](https://files.slack.com/files-pri/T029P2S9M-F060RDAB407/screenshot_20231014_135503_samsung_health.jpg)

![](https://files.slack.com/files-pri/T029P2S9M-F060ZA6Q2UE/screenshot_20231014_135436_samsung_health.jpg)

![](https://files.slack.com/files-pri/T029P2S9M-F060ZA6QF2S/screenshot_20231014_135352_samsung_health.jpg)

![](https://files.slack.com/files-pri/T029P2S9M-F060RDAC7U7/screenshot_20231014_135343_samsung_health.jpg)

![](https://files.slack.com/files-pri/T029P2S9M-F06131YL5GD/screenshot_20231014_135034_fit.jpg)

![](https://files.slack.com/files-pri/T029P2S9M-F0615V2N798/screenshot_20231014_135013_fit.jpg)

![](https://files.slack.com/files-pri/T029P2S9M-F0615S849H9/screenshot_20231014_134948_fit.jpg)

![](https://files.slack.com/files-pri/T029P2S9M-F060ZA6RW22/screenshot_20231014_134840_fit.jpg)

![](https://files.slack.com/files-pri/T029P2S9M-F0618CVC6DS/screenshot_20231014_134830_fit.jpg)

![](https://files.slack.com/files-pri/T029P2S9M-F0618CVCE0L/screenshot_20231014_134626.jpg)

![](https://files.slack.com/files-pri/T029P2S9M-F061JJF9U2D/screenshot_20231014_134620.jpg)

![](https://files.slack.com/files-pri/T029P2S9M-F060RDBBKAB/screenshot_20231014_134614.jpg) 

![](https://files.slack.com/files-pri/T029P2S9M-F061JJFACM7/screenshot_20231014_134519.jpg)

![](https://files.slack.com/files-pri/T029P2S9M-F0618CWAQTW/screenshot_20231014_134230_blogilates.jpg)

![](https://files.slack.com/files-pri/T029P2S9M-F060ZA7QXNJ/screenshot_20231014_134216_blogilates.jpg)

![](https://files.slack.com/files-pri/T029P2S9M-F0618CWB7KN/screenshot_20231014_134157_blogilates.jpg)

**Comment by tenthwalker** [comment]
https://coolors.co/fff8f0-9e2b25-51355a-2a0c4e-f5f8de

**Comment by tenthwalker** [comment]
https://fonts.google.com/specimen/Jaldi

**Comment by tenthwalker** [comment]
prefer the darker color backgrounds, minimalist design, clearly defined info card widgets
